spring:
  jpa: 
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.PostgreSQL81Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: docker
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
